// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { DateLike, DeliveryEstimateUnit } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​l​e​s​s​a​l​i​c​i​a​ ​A​r​t
	 */
	AppName: string
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
	 */
	'Sign in with Google': string
	Drawer: {
		/**
		 * O​v​e​r​v​i​e​w
		 */
		Overview: string
		/**
		 * O​r​d​e​r
		 */
		Order: string
		/**
		 * P​r​o​d​u​c​t
		 */
		Product: string
		/**
		 * S​h​i​p​p​i​n​g​ ​R​a​t​e
		 */
		'Shipping Rate': string
	}
	Overview: {
	}
	Order: {
	}
	Product: {
		/**
		 * N​a​m​e
		 */
		Name: string
		/**
		 * S​l​u​g
		 */
		Slug: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		Description: string
		/**
		 * I​m​a​g​e​s
		 */
		Images: string
		/**
		 * P​r​i​c​e
		 */
		Price: string
		/**
		 * C​u​r​r​e​n​c​y
		 */
		Currency: string
		/**
		 * S​h​i​p​p​i​n​g​ ​C​o​u​n​t​r​i​e​s
		 */
		ShippingCountries: string
		/**
		 * P​u​b​l​i​s​h​e​d​ ​a​t
		 */
		PublishedAt: string
		/**
		 * A​v​a​i​l​a​b​l​e
		 */
		Available: string
	}
	ShippingRate: {
		/**
		 * N​a​m​e
		 */
		Name: string
		/**
		 * P​r​i​c​e
		 */
		Price: string
		/**
		 * C​u​r​r​e​n​c​y
		 */
		Currency: string
		/**
		 * E​s​t​i​m​a​t​e
		 */
		Estimate: string
		Display: {
			/**
			 * {​d​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​M​i​n​V​a​l​}​ ​{​d​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​M​i​n​U​n​i​t​|​D​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​U​n​i​t​}​ ​-​ ​{​d​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​M​a​x​V​a​l​}​ ​{​d​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​M​a​x​U​n​i​t​|​D​e​l​i​v​e​r​y​E​s​t​i​m​a​t​e​U​n​i​t​}
			 * @param {DeliveryEstimateUnit} deliveryEstimateMaxUnit
			 * @param {number} deliveryEstimateMaxVal
			 * @param {DeliveryEstimateUnit} deliveryEstimateMinUnit
			 * @param {number} deliveryEstimateMinVal
			 */
			Estimate: RequiredParams<'deliveryEstimateMaxUnit|DeliveryEstimateUnit' | 'deliveryEstimateMaxVal' | 'deliveryEstimateMinUnit|DeliveryEstimateUnit' | 'deliveryEstimateMinVal'>
		}
	}
	DeliveryEstimateUnit: {
		/**
		 * B​u​s​i​n​e​s​s​ ​D​a​y
		 */
		business_day: string
		/**
		 * D​a​y
		 */
		day: string
		/**
		 * H​o​u​r
		 */
		hour: string
		/**
		 * M​o​n​t​h
		 */
		month: string
		/**
		 * W​e​e​k
		 */
		week: string
	}
	/**
	 * C​r​e​a​t​e
	 */
	Create: string
	/**
	 * S​e​a​r​c​h
	 */
	Search: string
	/**
	 * D​e​l​e​t​e
	 */
	Delete: string
	/**
	 * S​u​b​m​i​t
	 */
	Submit: string
	/**
	 * C​r​e​a​t​e​d​ ​a​t
	 */
	CreatedAt: string
	/**
	 * U​p​d​a​t​e​d​ ​a​t
	 */
	UpdatedAt: string
	/**
	 * {​0​|​d​a​t​e​}
	 * @param {DateLike} 0
	 */
	CreatedAtDate: RequiredParams<'0|date'>
	/**
	 * {​0​|​d​a​t​e​}
	 * @param {DateLike} 0
	 */
	UpdatedAtDate: RequiredParams<'0|date'>
	/**
	 * U​n​k​n​o​w​n​ ​E​r​r​o​r
	 */
	UnknownError: string
	Validation: {
		/**
		 * I​n​v​a​l​i​d​ ​v​a​l​u​e
		 */
		invalid_string: string
	}
}

export type TranslationFunctions = {
	/**
	 * Alessalicia Art
	 */
	AppName: () => LocalizedString
	/**
	 * Sign in with Google
	 */
	'Sign in with Google': () => LocalizedString
	Drawer: {
		/**
		 * Overview
		 */
		Overview: () => LocalizedString
		/**
		 * Order
		 */
		Order: () => LocalizedString
		/**
		 * Product
		 */
		Product: () => LocalizedString
		/**
		 * Shipping Rate
		 */
		'Shipping Rate': () => LocalizedString
	}
	Overview: {
	}
	Order: {
	}
	Product: {
		/**
		 * Name
		 */
		Name: () => LocalizedString
		/**
		 * Slug
		 */
		Slug: () => LocalizedString
		/**
		 * Description
		 */
		Description: () => LocalizedString
		/**
		 * Images
		 */
		Images: () => LocalizedString
		/**
		 * Price
		 */
		Price: () => LocalizedString
		/**
		 * Currency
		 */
		Currency: () => LocalizedString
		/**
		 * Shipping Countries
		 */
		ShippingCountries: () => LocalizedString
		/**
		 * Published at
		 */
		PublishedAt: () => LocalizedString
		/**
		 * Available
		 */
		Available: () => LocalizedString
	}
	ShippingRate: {
		/**
		 * Name
		 */
		Name: () => LocalizedString
		/**
		 * Price
		 */
		Price: () => LocalizedString
		/**
		 * Currency
		 */
		Currency: () => LocalizedString
		/**
		 * Estimate
		 */
		Estimate: () => LocalizedString
		Display: {
			/**
			 * {deliveryEstimateMinVal} {deliveryEstimateMinUnit|DeliveryEstimateUnit} - {deliveryEstimateMaxVal} {deliveryEstimateMaxUnit|DeliveryEstimateUnit}
			 */
			Estimate: (arg: { deliveryEstimateMaxUnit: DeliveryEstimateUnit, deliveryEstimateMaxVal: number, deliveryEstimateMinUnit: DeliveryEstimateUnit, deliveryEstimateMinVal: number }) => LocalizedString
		}
	}
	DeliveryEstimateUnit: {
		/**
		 * Business Day
		 */
		business_day: () => LocalizedString
		/**
		 * Day
		 */
		day: () => LocalizedString
		/**
		 * Hour
		 */
		hour: () => LocalizedString
		/**
		 * Month
		 */
		month: () => LocalizedString
		/**
		 * Week
		 */
		week: () => LocalizedString
	}
	/**
	 * Create
	 */
	Create: () => LocalizedString
	/**
	 * Search
	 */
	Search: () => LocalizedString
	/**
	 * Delete
	 */
	Delete: () => LocalizedString
	/**
	 * Submit
	 */
	Submit: () => LocalizedString
	/**
	 * Created at
	 */
	CreatedAt: () => LocalizedString
	/**
	 * Updated at
	 */
	UpdatedAt: () => LocalizedString
	/**
	 * {0|date}
	 */
	CreatedAtDate: (arg0: DateLike) => LocalizedString
	/**
	 * {0|date}
	 */
	UpdatedAtDate: (arg0: DateLike) => LocalizedString
	/**
	 * Unknown Error
	 */
	UnknownError: () => LocalizedString
	Validation: {
		/**
		 * Invalid value
		 */
		invalid_string: () => LocalizedString
	}
}

export type Formatters = {
	date: (value: DateLike) => unknown
	DeliveryEstimateUnit: (value: DeliveryEstimateUnit) => unknown
}
